from __future__ import annotations

from cryptolab.features.registry import (
    AvailabilityPolicy,
    FeatureKind,
    FeatureParameter,
    FeatureRegistry,
    FeatureSpec,
)


FEATURE_SPECS = (
    # ============================================================
    # PRICE / STRUCTURE
    # ============================================================

    FeatureSpec(
        feature_id="price.core",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.price:"
            "build_price_features"
        ),
        kind=FeatureKind.FEATURE,
        category="price",
        input_datasets=(
            "binance.ohlcv",
        ),
        input_features=(),
        output_columns=(
            "simple_return",
            "log_return",
            "true_range",
            "daily_vwap",
            "weekly_vwap",
            "monthly_vwap",
            "rv_30d_zscore_1y",
            "rv_30d_percentile_1y",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="atr_window",
                default="14",
            ),
            FeatureParameter(
                name="rolling_windows",
                default="(24, 168, 720)",
            ),
        ),
        description=(
            "Canonical price returns, ranges, volatility, "
            "rolling-location and VWAP feature family."
        ),
        tags=(
            "price",
            "volatility",
            "vwap",
        ),
    ),

    FeatureSpec(
        feature_id="price.market_structure",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.market_structure:"
            "add_market_structure_features"
        ),
        kind=FeatureKind.FEATURE,
        category="structure",
        input_datasets=(
            "binance.ohlcv",
        ),
        input_features=(),
        output_columns=(
            "confirmed_swing_high",
            "confirmed_swing_low",
            "swing_event",
            "swing_kind",
            "swing_price",
            "swing_time",
            "swing_confirmation_time",
            "structure_label",
            "swing_window_valid",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="left_bars",
                default="3",
            ),
            FeatureParameter(
                name="right_bars",
                default="3",
            ),
            FeatureParameter(
                name="expected_interval_hours",
                default="1",
            ),
        ),
        description=(
            "Confirmed swing and market-structure event layer."
        ),
        tags=(
            "structure",
            "swing",
        ),
    ),

    FeatureSpec(
        feature_id="price.structural_levels",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.structural_levels:"
            "add_structural_level_features"
        ),
        kind=FeatureKind.FEATURE,
        category="structure",
        input_datasets=(),
        input_features=(
            "price.market_structure",
        ),
        output_columns=(
            "active_support",
            "active_resistance",
            "structural_range",
            "structural_range_pct",
            "structural_range_position",
            "structural_range_valid",
            "nearest_structure_side",
            "nearest_structure_distance_pct",
            "range_state",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        description=(
            "Active support/resistance and structural-range "
            "location features."
        ),
        tags=(
            "structure",
            "levels",
        ),
    ),

    FeatureSpec(
        feature_id="price.structural_state",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.structural_state:"
            "add_structural_state_features"
        ),
        kind=FeatureKind.FEATURE,
        category="structure",
        input_datasets=(),
        input_features=(
            "price.market_structure",
        ),
        output_columns=(
            "structure_state",
            "structural_break",
            "break_direction",
            "break_level",
            "bos",
            "bos_direction",
            "choch",
            "choch_direction",
            "initial_structure_break",
            "state_changed",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        description=(
            "Structural state, BOS and CHoCH feature layer."
        ),
        tags=(
            "structure",
            "bos",
            "choch",
        ),
    ),

    FeatureSpec(
        feature_id="price.quality",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.quality_masks:"
            "add_price_quality_masks"
        ),
        kind=FeatureKind.QUALITY,
        category="price",
        input_datasets=(),
        input_features=(
            "price.core",
        ),
        output_columns=(
            "source_gap_before",
            "source_irregular_before",
            "missing_hours_before",
            "atr_14_valid",
            "atr_14_pct_valid",
            "rv_30d_zscore_1y_valid",
            "rv_30d_percentile_1y_valid",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.PASSTHROUGH
        ),
        parameters=(
            FeatureParameter(
                name="expected_interval_hours",
                default="1",
            ),
        ),
        description=(
            "Price feature validity and source-quality masks."
        ),
        tags=(
            "quality",
            "price",
        ),
    ),

    FeatureSpec(
        feature_id="price.regime",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.regime:"
            "add_price_regime_features"
        ),
        kind=FeatureKind.REGIME,
        category="price",
        input_datasets=(),
        input_features=(
            "price.core",
            "price.structural_levels",
            "price.structural_state",
        ),
        output_columns=(
            "volatility_regime",
            "location_regime",
            "price_regime",
            "regime_confidence",
            "price_regime_valid",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        description=(
            "Descriptive price regime built from volatility, "
            "location and structural state."
        ),
        tags=(
            "regime",
            "price",
        ),
    ),

    FeatureSpec(
        feature_id="price.snapshot",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.snapshot:"
            "build_price_snapshot"
        ),
        kind=FeatureKind.SNAPSHOT,
        category="price",
        input_datasets=(),
        input_features=(
            "price.core",
            "price.market_structure",
            "price.structural_levels",
            "price.structural_state",
            "price.quality",
            "price.regime",
        ),
        output_columns=(
            "open_time",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        description=(
            "Latest price research-state read model."
        ),
        tags=(
            "snapshot",
            "read_model",
        ),
    ),

    # ============================================================
    # TRADE FLOW
    # ============================================================

    FeatureSpec(
        feature_id="trade_flow.aggregate",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.trade_flow:"
            "aggregate_aggtrades"
        ),
        kind=FeatureKind.AGGREGATION,
        category="trade_flow",
        input_datasets=(
            "binance.aggtrades",
        ),
        input_features=(),
        output_columns=(
            "base_delta",
            "quote_delta",
            "base_delta_pct",
            "quote_delta_pct",
            "trade_count_imbalance",
            "buy_quote_ratio",
            "sell_quote_ratio",
            "buy_trade_ratio",
            "sell_trade_ratio",
            "vwap",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="timeframe",
                default="<required>",
            ),
        ),
        description=(
            "Aggregate raw aggTrades into canonical trade-flow "
            "interval features."
        ),
        tags=(
            "trade_flow",
            "aggregation",
        ),
    ),

    FeatureSpec(
        feature_id="trade_flow.cvd",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.trade_flow:"
            "add_cvd_features"
        ),
        kind=FeatureKind.FEATURE,
        category="trade_flow",
        input_datasets=(),
        input_features=(
            "trade_flow.aggregate",
        ),
        output_columns=(
            "base_cvd",
            "quote_cvd",
            "daily_base_cvd",
            "daily_quote_cvd",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.PASSTHROUGH
        ),
        description=(
            "Cumulative-volume-delta feature family."
        ),
        tags=(
            "trade_flow",
            "cvd",
        ),
    ),

    FeatureSpec(
        feature_id="trade_flow.large_trade_flags",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.large_trades:"
            "add_large_trade_flags"
        ),
        kind=FeatureKind.FEATURE,
        category="trade_flow",
        input_datasets=(
            "binance.aggtrades",
        ),
        input_features=(),
        output_columns=(
            "trade_notional",
            "large_trade_threshold",
            "very_large_trade_threshold",
            "large_trade",
            "very_large_trade",
            "large_buy",
            "large_sell",
            "very_large_buy",
            "very_large_sell",
        ),
        event_time_column="trade_time",
        availability_policy=(
            AvailabilityPolicy.PASSTHROUGH
        ),
        parameters=(
            FeatureParameter(
                name="rolling_window",
                default="10000",
            ),
            FeatureParameter(
                name="large_quantile",
                default="0.95",
            ),
            FeatureParameter(
                name="very_large_quantile",
                default="0.99",
            ),
            FeatureParameter(
                name="min_periods",
                default="1000",
            ),
        ),
        description=(
            "Point-in-time rolling large-trade classification."
        ),
        tags=(
            "trade_flow",
            "large_trade",
        ),
    ),

    FeatureSpec(
        feature_id="trade_flow.large_trade_aggregate",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.large_trades:"
            "aggregate_large_trade_features"
        ),
        kind=FeatureKind.AGGREGATION,
        category="trade_flow",
        input_datasets=(),
        input_features=(
            "trade_flow.large_trade_flags",
        ),
        output_columns=(
            "large_trade_share",
            "large_trade_quote_share",
            "large_quote_delta",
            "very_large_trade_share",
            "very_large_trade_quote_share",
            "very_large_quote_delta",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="timeframe",
                default="1m",
            ),
        ),
        description=(
            "Interval aggregation of large-trade activity."
        ),
        tags=(
            "trade_flow",
            "large_trade",
            "aggregation",
        ),
    ),

    FeatureSpec(
        feature_id="trade_flow.regime",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.trade_flow_regime:"
            "add_trade_flow_regime_features"
        ),
        kind=FeatureKind.REGIME,
        category="trade_flow",
        input_datasets=(),
        input_features=(
            "trade_flow.aggregate",
            "trade_flow.cvd",
        ),
        optional_input_features=(
            "trade_flow.large_trade_aggregate",
        ),
        output_columns=(
            "rolling_quote_delta_60",
            "rolling_quote_volume_60",
            "rolling_quote_imbalance_60",
            "large_quote_delta",
            "large_quote_delta_pct",
            "large_trade_quote_share",
            "trade_flow_regime",
            "flow_regime_confidence",
            "trade_flow_regime_valid",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="rolling_window",
                default="60",
            ),
            FeatureParameter(
                name="delta_threshold",
                default="0.15",
            ),
            FeatureParameter(
                name="count_threshold",
                default="0.1",
            ),
            FeatureParameter(
                name="balanced_threshold",
                default="0.1",
            ),
            FeatureParameter(
                name="large_share_threshold",
                default="0.2",
            ),
            FeatureParameter(
                name="large_delta_threshold",
                default="0.25",
            ),
        ),
        description=(
            "Trade-flow state/regime classification."
        ),
        tags=(
            "trade_flow",
            "regime",
        ),
    ),

    FeatureSpec(
        feature_id="trade_flow.snapshot",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.trade_flow_snapshot:"
            "build_trade_flow_snapshot"
        ),
        kind=FeatureKind.SNAPSHOT,
        category="trade_flow",
        input_datasets=(),
        input_features=(
            "trade_flow.aggregate",
            "trade_flow.cvd",
            "trade_flow.regime",
        ),
        output_columns=(
            "open_time",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        description=(
            "Latest trade-flow research-state read model."
        ),
        tags=(
            "snapshot",
            "read_model",
        ),
    ),

    # ============================================================
    # DERIVATIVES
    # ============================================================

    FeatureSpec(
        feature_id="derivatives.core",
        version="1.1.0",
        callable_path=(
            "cryptolab.features.derivatives:"
            "build_derivatives_features"
        ),
        kind=FeatureKind.FEATURE,
        category="derivatives",
        input_datasets=(
            "binance.open_interest",
            "binance.funding_rate",
            "binance.basis",
            "binance.taker_flow",
            "binance.liquidations",
        ),
        input_features=(),
        output_columns=(
            "open_interest_quote",
            "open_interest_base",
            "oi_base_change",
            "oi_base_change_pct",
            "oi_quote_change",
            "oi_quote_change_pct",
            "oi_quote_zscore_24h",
            "funding_time",
            "funding_rate",
            "funding_rate_bps",
            "basis_rate",
            "basis_bps",
            "basis_zscore_24h",
            "futures_taker_delta",
            "futures_taker_delta_pct",
            "total_liquidation_notional",
            "liquidation_delta",
            "liquidation_imbalance",
            "available_at",
        ),
        event_time_column="timestamp",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        description=(
            "Canonical multi-source derivatives feature layer. "
            "Emits available_at as the maximum availability of "
            "the raw observations actually consumed by each "
            "row."
        ),
        tags=(
            "derivatives",
            "funding",
            "basis",
            "oi",
            "liquidation",
        ),
    ),

    FeatureSpec(
        feature_id="derivatives.price_oi_state",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.price_oi_state:"
            "build_price_oi_state"
        ),
        kind=FeatureKind.FEATURE,
        category="derivatives",
        input_datasets=(),
        input_features=(
            "price.core",
            "derivatives.core",
        ),
        output_columns=(
            "price_return_1h",
            "oi_base_change_1h",
            "oi_base_change_pct_1h",
            "oi_quote_change_1h",
            "oi_quote_change_pct_1h",
            "price_direction",
            "oi_direction",
            "price_oi_state",
            "price_oi_strength",
            "price_oi_state_valid",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="price_threshold",
                default="0.001",
            ),
            FeatureParameter(
                name="oi_threshold",
                default="0.002",
            ),
        ),
        description=(
            "Joint price/open-interest directional state."
        ),
        tags=(
            "derivatives",
            "open_interest",
            "state",
        ),
    ),

    FeatureSpec(
        feature_id="derivatives.spot_perp_state",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.spot_perp_flow:"
            "build_spot_perp_flow_state"
        ),
        kind=FeatureKind.FEATURE,
        category="derivatives",
        input_datasets=(),
        input_features=(
            "trade_flow.aggregate",
            "derivatives.core",
        ),
        output_columns=(
            "spot_flow_strength",
            "perp_flow_strength",
            "spot_perp_combined_strength",
            "spot_perp_delta_agreement",
            "spot_perp_delta_spread",
            "spot_perp_flow_state",
            "spot_perp_flow_valid",
        ),
        event_time_column="timestamp",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="directional_threshold",
                default="0.1",
            ),
            FeatureParameter(
                name="leadership_ratio",
                default="1.5",
            ),
        ),
        description=(
            "Relative spot-versus-perpetual flow state."
        ),
        tags=(
            "derivatives",
            "spot_perp",
            "flow",
        ),
    ),

    FeatureSpec(
        feature_id="derivatives.regime",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.derivatives_regime:"
            "build_derivatives_regime"
        ),
        kind=FeatureKind.REGIME,
        category="derivatives",
        input_datasets=(),
        input_features=(
            "derivatives.price_oi_state",
            "derivatives.spot_perp_state",
            "derivatives.core",
        ),
        output_columns=(
            "derivatives_regime",
            "derivatives_regime_confidence",
            "derivatives_regime_valid",
            "liquidation_extreme",
            "liquidation_threshold_24h",
            "long_support_count",
            "short_support_count",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="flow_threshold",
                default="0.1",
            ),
            FeatureParameter(
                name="liquidation_imbalance_threshold",
                default="0.5",
            ),
        ),
        description=(
            "Canonical 1h derivatives-state classification."
        ),
        tags=(
            "derivatives",
            "regime",
        ),
    ),

    FeatureSpec(
        feature_id="derivatives.quality",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.derivatives_quality:"
            "add_derivatives_quality_masks"
        ),
        kind=FeatureKind.QUALITY,
        category="derivatives",
        input_datasets=(),
        input_features=(
            "derivatives.regime",
        ),
        output_columns=(
            "oi_valid",
            "funding_valid",
            "basis_valid",
            "taker_flow_valid",
            "spot_perp_valid",
            "liquidation_valid",
            "derivatives_core_valid",
            "derivatives_quality_score",
            "derivatives_quality_tier",
            "derivatives_regime_quality_valid",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.PASSTHROUGH
        ),
        parameters=(
            FeatureParameter(
                name="funding_max_age_hours",
                default="12.0",
            ),
            FeatureParameter(
                name="spot_perp_min_valid_share",
                default="0.8",
            ),
        ),
        description=(
            "Quality and causal-validity layer for derivatives "
            "research features."
        ),
        tags=(
            "derivatives",
            "quality",
        ),
    ),

    FeatureSpec(
        feature_id="derivatives.liquidation_coverage",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.derivatives_liquidation_coverage:"
            "apply_liquidation_coverage"
        ),
        kind=FeatureKind.QUALITY,
        category="derivatives",
        input_datasets=(
            "binance.liquidation_heartbeat",
        ),
        input_features=(
            "derivatives.quality",
        ),
        output_columns=(
            "liquidation_coverage_ratio",
            "liquidation_collector_covered",
            "liquidation_observed",
            "liquidation_valid",
            "derivatives_quality_score",
            "derivatives_quality_tier",
            "derivatives_regime_quality_valid",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        description=(
            "Collector-coverage enrichment preventing missing "
            "liquidation data from being interpreted as zero."
        ),
        tags=(
            "derivatives",
            "quality",
            "coverage",
        ),
    ),

    FeatureSpec(
        feature_id="derivatives.snapshot",
        version="1.0.0",
        callable_path=(
            "cryptolab.features.derivatives_snapshot:"
            "build_derivatives_snapshot"
        ),
        kind=FeatureKind.SNAPSHOT,
        category="derivatives",
        input_datasets=(),
        input_features=(
            "derivatives.regime",
            "derivatives.liquidation_coverage",
        ),
        output_columns=(
            "open_time",
            "as_of_time",
        ),
        event_time_column="open_time",
        availability_policy=(
            AvailabilityPolicy.MAX_INPUT_AVAILABLE_AT
        ),
        parameters=(
            FeatureParameter(
                name="exchange",
                default="binance",
            ),
            FeatureParameter(
                name="symbol",
                default="BTCUSDT",
            ),
            FeatureParameter(
                name="timeframe",
                default="1h",
            ),
        ),
        description=(
            "Latest derivatives research-state read model."
        ),
        tags=(
            "snapshot",
            "read_model",
            "derivatives",
        ),
    ),
)


FEATURE_REGISTRY = FeatureRegistry(
    FEATURE_SPECS
)


def get_feature_registry() -> FeatureRegistry:
    """
    Return the canonical CryptoLab feature registry.

    The registry itself is immutable by convention at the catalog
    layer. Callers that need an isolated mutable registry should
    construct a new FeatureRegistry from FEATURE_SPECS.
    """

    return FEATURE_REGISTRY
